
Description: 
  "Dynamo DB table for spider records and a stream for processing them later"
Resources :
  SpiderMapsDynamo :
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "SpiderMapsDynamo"
      AttributeDefinitions:
        -
          AttributeName: "Guid"
          AttributeType: "S"
        -
          AttributeName: "User"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Guid"
          KeyType: "HASH"
        -
          AttributeName: "User"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits : 5
		WriteCapacityUnits : 5
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
Outputs:
  DyanmoDBName:
    Description: "Name of the database"
    Value: !Ref SpiderMapsDynamo
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "DynamoDBName" ] ]

  DynamoDBArn:
    Description: "Arn of the database"
    Value: !GetAtt SpiderMapsDynamo.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "DynamoDBArn" ] ]

  DynamoDBStreamArn:
    Description: "Arn of the stream"
    Value: !GetAtt SpiderMapsDyname.StreamArn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "DynamoStreamArn" ] ]